package CalculadoraApp;


/**
* CalculadoraApp/CalculadoraServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcApp.idl
* Quinta-feira, 12 de Setembro de 2019 10h00min02s BRT
*/

public interface CalculadoraServerOperations 
{
  int somar (int a, int b);
  int subtrair (int a, int b);
  int multiplicar (int a, int b);
  double dividir (int a, int b);
} // interface CalculadoraServerOperations
