package CalculadoraApp;


/**
* CalculadoraApp/CalculadoraServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcApp.idl
* Quinta-feira, 19 de Setembro de 2019 08h11min17s BRT
*/

abstract public class CalculadoraServerHelper
{
  private static String  _id = "IDL:CalculadoraApp/CalculadoraServer:1.0";

  public static void insert (org.omg.CORBA.Any a, CalculadoraApp.CalculadoraServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CalculadoraApp.CalculadoraServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CalculadoraApp.CalculadoraServerHelper.id (), "CalculadoraServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CalculadoraApp.CalculadoraServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CalculadoraServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CalculadoraApp.CalculadoraServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CalculadoraApp.CalculadoraServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CalculadoraApp.CalculadoraServer)
      return (CalculadoraApp.CalculadoraServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CalculadoraApp._CalculadoraServerStub stub = new CalculadoraApp._CalculadoraServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CalculadoraApp.CalculadoraServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CalculadoraApp.CalculadoraServer)
      return (CalculadoraApp.CalculadoraServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CalculadoraApp._CalculadoraServerStub stub = new CalculadoraApp._CalculadoraServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
