package cadastroPessoa.PessoaDAOPackage;


/**
* cadastroPessoa/PessoaDAOPackage/PessoaRetorno.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cadastro.idl
* Quinta-feira, 19 de Setembro de 2019 08h52min01s BRT
*/

public final class PessoaRetorno implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String nome = null;
  public String email = null;

  public PessoaRetorno ()
  {
  } // ctor

  public PessoaRetorno (int _id, String _nome, String _email)
  {
    id = _id;
    nome = _nome;
    email = _email;
  } // ctor

} // class PessoaRetorno
