package CalculadoraApp;


/**
* CalculadoraApp/CalculadoraServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcApp.idl
* Quinta-feira, 12 de Setembro de 2019 09h59min30s BRT
*/

public interface CalculadoraServer extends CalculadoraServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CalculadoraServer
