package CalculadoraApp;


/**
* CalculadoraApp/CalculadoraServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcApp.idl
* Quinta-feira, 12 de Setembro de 2019 09h59min30s BRT
*/

public abstract class CalculadoraServerPOA extends org.omg.PortableServer.Servant
 implements CalculadoraApp.CalculadoraServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("somar", new java.lang.Integer (0));
    _methods.put ("subtrair", new java.lang.Integer (1));
    _methods.put ("multiplicar", new java.lang.Integer (2));
    _methods.put ("dividir", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CalculadoraApp/CalculadoraServer/somar
       {
         int a = in.read_long ();
         int b = in.read_long ();
         int $result = (int)0;
         $result = this.somar (a, b);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // CalculadoraApp/CalculadoraServer/subtrair
       {
         int a = in.read_long ();
         int b = in.read_long ();
         int $result = (int)0;
         $result = this.subtrair (a, b);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // CalculadoraApp/CalculadoraServer/multiplicar
       {
         int a = in.read_long ();
         int b = in.read_long ();
         int $result = (int)0;
         $result = this.multiplicar (a, b);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // CalculadoraApp/CalculadoraServer/dividir
       {
         int a = in.read_long ();
         int b = in.read_long ();
         double $result = (double)0;
         $result = this.dividir (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CalculadoraApp/CalculadoraServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CalculadoraServer _this() 
  {
    return CalculadoraServerHelper.narrow(
    super._this_object());
  }

  public CalculadoraServer _this(org.omg.CORBA.ORB orb) 
  {
    return CalculadoraServerHelper.narrow(
    super._this_object(orb));
  }


} // class CalculadoraServerPOA
