package cadastroPessoa;


/**
* cadastroPessoa/PessoaDAOPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cadastro.idl
* Quinta-feira, 19 de Setembro de 2019 08h21min34s BRT
*/

public abstract class PessoaDAOPOA extends org.omg.PortableServer.Servant
 implements cadastroPessoa.PessoaDAOOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("PessoaDAO", new java.lang.Integer (0));
    _methods.put ("adicionar", new java.lang.Integer (1));
    _methods.put ("remover", new java.lang.Integer (2));
    _methods.put ("pesquisar", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // cadastroPessoa/PessoaDAO/PessoaDAO
       {
         this.PessoaDAO ();
         out = $rh.createReply();
         break;
       }

       case 1:  // cadastroPessoa/PessoaDAO/adicionar
       {
         cadastroPessoa.Pessoa pessoa = cadastroPessoa.PessoaHelper.read (in);
         this.adicionar (pessoa);
         out = $rh.createReply();
         break;
       }

       case 2:  // cadastroPessoa/PessoaDAO/remover
       {
         String nomePessoa = in.read_string ();
         this.remover (nomePessoa);
         out = $rh.createReply();
         break;
       }

       case 3:  // cadastroPessoa/PessoaDAO/pesquisar
       {
         String nomePessoa = in.read_string ();
         cadastroPessoa.PessoaDAOPackage.PessoaRetorno $result = null;
         $result = this.pesquisar (nomePessoa);
         out = $rh.createReply();
         cadastroPessoa.PessoaDAOPackage.PessoaRetornoHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:cadastroPessoa/PessoaDAO:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PessoaDAO _this() 
  {
    return PessoaDAOHelper.narrow(
    super._this_object());
  }

  public PessoaDAO _this(org.omg.CORBA.ORB orb) 
  {
    return PessoaDAOHelper.narrow(
    super._this_object(orb));
  }


} // class PessoaDAOPOA
