package cadastroPessoa;


/**
* cadastroPessoa/PessoaDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cadastro.idl
* Quinta-feira, 19 de Setembro de 2019 08h21min34s BRT
*/

public interface PessoaDAOOperations 
{
  void PessoaDAO ();
  void adicionar (cadastroPessoa.Pessoa pessoa);
  void remover (String nomePessoa);
  cadastroPessoa.PessoaDAOPackage.PessoaRetorno pesquisar (String nomePessoa);
} // interface PessoaDAOOperations
