package cadastroPessoa;


/**
* cadastroPessoa/PessoaDAO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cadastro.idl
* Quinta-feira, 19 de Setembro de 2019 08h21min34s BRT
*/

public interface PessoaDAO extends PessoaDAOOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PessoaDAO
