package cadastroPessoa;

/**
* cadastroPessoa/PessoaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cadastro.idl
* Quinta-feira, 19 de Setembro de 2019 08h21min34s BRT
*/

public final class PessoaHolder implements org.omg.CORBA.portable.Streamable
{
  public cadastroPessoa.Pessoa value = null;

  public PessoaHolder ()
  {
  }

  public PessoaHolder (cadastroPessoa.Pessoa initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cadastroPessoa.PessoaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cadastroPessoa.PessoaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cadastroPessoa.PessoaHelper.type ();
  }

}
