package cadastroPessoa.PessoaDAOPackage;

/**
* cadastroPessoa/PessoaDAOPackage/PessoaRetornoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cadastro.idl
* Quinta-feira, 19 de Setembro de 2019 08h21min34s BRT
*/

public final class PessoaRetornoHolder implements org.omg.CORBA.portable.Streamable
{
  public cadastroPessoa.PessoaDAOPackage.PessoaRetorno value = null;

  public PessoaRetornoHolder ()
  {
  }

  public PessoaRetornoHolder (cadastroPessoa.PessoaDAOPackage.PessoaRetorno initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cadastroPessoa.PessoaDAOPackage.PessoaRetornoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cadastroPessoa.PessoaDAOPackage.PessoaRetornoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cadastroPessoa.PessoaDAOPackage.PessoaRetornoHelper.type ();
  }

}
