package cadastroPessoa;


/**
* cadastroPessoa/PessoaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cadastro.idl
* Quinta-feira, 19 de Setembro de 2019 08h52min01s BRT
*/

public interface PessoaOperations 
{
  void Pessoa ();
  int getId ();
  void setId (int id);
  String getNome ();
  void setNome (String nome);
  String getEmail ();
  void setEmail (String email);
} // interface PessoaOperations
