package cadastroPessoa;


/**
* cadastroPessoa/Pessoa.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cadastro.idl
* Quinta-feira, 19 de Setembro de 2019 08h52min01s BRT
*/

public interface Pessoa extends PessoaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Pessoa
