package cadastroPessoa;

/**
* cadastroPessoa/PessoaDAOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cadastro.idl
* Quinta-feira, 19 de Setembro de 2019 08h52min01s BRT
*/

public final class PessoaDAOHolder implements org.omg.CORBA.portable.Streamable
{
  public cadastroPessoa.PessoaDAO value = null;

  public PessoaDAOHolder ()
  {
  }

  public PessoaDAOHolder (cadastroPessoa.PessoaDAO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cadastroPessoa.PessoaDAOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cadastroPessoa.PessoaDAOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cadastroPessoa.PessoaDAOHelper.type ();
  }

}
