package hello;


/**
* hello/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Quinta-feira, 12 de Setembro de 2019 09h50min56s BRT
*/

public interface HelloOperations 
{
  void say_hello ();
  String say_this (String msg);
} // interface HelloOperations
