package hello;


/**
* hello/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Quarta-feira, 11 de Setembro de 2019 08h24min08s BRT
*/

public interface HelloOperations 
{
  void say_hello ();
} // interface HelloOperations
